apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lzkdb8k07-java-springboot 
  janus-idp.io/tekton: lzkdb8k07-java-springboot
  backstage.io/kubernetes-id: lzkdb8k07-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lzkdb8k07-java-springboot
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  