apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: lzkdb8k07-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:dd02d72e0c64dac19cf5446c9de24b2eea6566fd@sha256:46435d0c57e31a426728ca6068b3a537cd71133364e58b9f5dfec137b2e15cfb
          name: container-image
